/*
import Game from '../classes/Game'
export const DefaultGameState = (): Game => {
    mapId: 0,
    width: 795,
    height: 555,
    maps: [{
        name: 'Dragon\'s Lair',
        id: 0,
        imageUrl: 'https://mk0a2minutetabl7hq7i.kinstacdn.com/wp-content/uploads/2022/02/Arena-of-Fire-battle-map-Main-preview-Night.jpg',
        x: 0,
        y: 0,
        width: 795,
        height: 555,
        drawPaths: [],
        fogPaths: [],
    },
    {
        name: 'Mage Tower',
        id: 1,
        imageUrl: 'https://2minutetabletop.com/wp-content/uploads/2022/01/Wizarding-School-Classroom-Basic-Light-16x22-1.jpg',
        x: 0,
        y: 0,
        width: 795,
        height: 555,
        drawPaths: [],
        fogPaths: [],
    }],
    tokens: [{
        guid: guid(),
        name: 'Adult Black Dragon',
        url: 'https://i.imgur.com/H2dyKur.png',
        mapId: 0,
        x: 350,
        y: 210,
        ko: false,
        pc: false,
        width: 100,
        height: 100,
        size: 'huge',
        selected: false,
        hidden: false,
        showLabel: true,
        x0: 0,
        y0: 0,
    },
    {
        guid: guid(),
        name: 'Mighty Paladin',
        url: 'https://i.imgur.com/ccQxtZ7.png',
        mapId: 0,
        x: 50,
        y: 180,
        ko: false,
        pc: true,
        width: 50,
        height: 50,
        size: 'medium',
        selected: false,
        hidden: false,
        showLabel: false,
        x0: 0,
        y0: 0,
    },
    {
        guid: guid(),
        name: 'Misterious Wizard',
        url: 'https://i.imgur.com/82s9UPR.png',
        mapId: 1,
        x: 620,
        y: 250,
        ko: false,
        pc: false,
        width: 50,
        height: 50,
        size: 'medium',
        selected: false,
        hidden: false,
        showLabel: true,
        x0: 0,
        y0: 0,
    }]
}

export default DefaultGameState
*/
