// settings
export const CHANGE_CURSORSIZE = 'SETTINGS/CHANGE_CURSORSIZE'
export const CHANGE_FOG_SETTINGS = 'SETTINGS/CHANGE_FOG_SETTINGS'
export const CHANGE_DRAW_SETTINGS = 'SETTINGS/CHANGE_DRAW_SETTINGS'
export const CHANGE_TOOL = 'SETTINGS/CHANGE_TOOL'
export const CHANGE_USERNAME = 'SETTINGS/CHANGE_USERNAME'
export const TOGGLE_MOUSESHARING = 'SETTINGS/TOGGLE_MOUSESHARING'

// game
export const OVERWRITE_GAME = 'GAME/OVERWRITE_GAME'
export const LOAD_MAP = 'GAME/LOAD_MAP'
export const INCREMENT_GEN = 'GAME/INCREMENT_GEN'
export const SET_FOG_ENABLED = 'GAME/SET_FOG_ENABLED'
export const SET_ISFOGLOADED = 'GAME/SET_ISFOGLOADED'
export const SET_ISFIRSTLOADDONE = 'GAME/SET_ISFIRSTLOADDONE'
export const UPDATE_MAPS = 'GAME/UPDATE_MAPS'
export const ADD_MAP = 'GAME/ADD_MAP'
export const DELETE_MAP = 'GAME/DELETE_APP'
export const UPDATE_TOKENS = 'GAME/UPDATE_TOKENS'
export const ADD_TOKEN = 'GAME/ADD_TOKEN'
export const DELETE_TOKEN = 'GAME/DELETE_TOKEN'
export const COPY_TOKEN = 'GAME/COPY_TOKEN'
export const UPDATE_TOKEN_VALUE = 'GAME/UPDATE_TOKEN_VALUE'
export const TOGGLE_TOKEN_VALUE = 'GAME/TOGGLE_TOKEN_VALUE'
export const SET_TOKEN_ORIGIN = 'GAME/SET_TOKEN_ORIGIN'
export const RESET_FOG = 'GAME/RESET_FOG'
export const RESET_DRAW = 'GAME/RESET_DRAW'

// metadata
export const SET_GAMESETTINGS = 'METADATA/SET_GAMESETTINGS'
export const SET_ISHOST = 'METADATA/SET_ISHOST'
export const SET_ROOM = 'METADATA/ROOM'
export const SET_CURSORS = 'METADATA/SET_CURSORS'
export const SET_LAST_COORDINATES = 'METADATA/SET_LAST_COORDINATES'
export const SET_DOWN_COORDINATES = 'METADATA/SET_DOWN_COORDINATES'

// controlpanel
//TODO: Add control panel actions
