// settings
export const CHANGE_CURSORSIZE = 'SETTINGS/CHANGE_CURSORSIZE'
export const CHANGE_FOG_SETTINGS = 'SETTINGS/CHANGE_FOG_SETTINGS'
export const CHANGE_DRAW_SETTINGS = 'SETTINGS/CHANGE_DRAW_SETTINGS'
export const CHANGE_TOOL = 'SETTINGS/CHANGE_TOOL'
export const CHANGE_USERNAME = 'SETTINGS/CHANGE_USERNAME'
export const TOGGLE_MOUSESHARING = 'SETTINGS/TOGGLE_MOUSESHARING'
export const UPDATE_DELTAXY = 'SETTINGS/UPDATE_DELTAXY'
export const UPDATE_SCALE = 'SETTINGS/UPDATE_SCALE'

// game
export const OVERWRITE_GAME = 'GAME/OVERWRITE_GAME'
export const LOAD_MAP = 'GAME/LOAD_MAP'
export const INCREMENT_GEN = 'GAME/INCREMENT_GEN'
export const SET_FOG_ENABLED = 'GAME/SET_FOG_ENABLED'
export const UPDATE_MAPS = 'GAME/UPDATE_MAPS'
export const ADD_MAP = 'GAME/ADD_MAP'
export const DELETE_MAP = 'GAME/DELETE_APP'
export const UPDATE_TOKENS = 'GAME/UPDATE_TOKENS'
export const ADD_TOKEN = 'GAME/ADD_TOKEN'
export const DELETE_TOKEN = 'GAME/DELETE_TOKEN'
export const COPY_TOKEN = 'GAME/COPY_TOKEN'
export const UPDATE_TOKEN_VALUE = 'GAME/UPDATE_TOKEN_VALUE'
export const TOGGLE_TOKEN_VALUE = 'GAME/TOGGLE_TOKEN_VALUE'
export const SET_TOKEN_ORIGIN = 'GAME/SET_TOKEN_ORIGIN'
export const RESET_FOG = 'GAME/RESET_FOG'
export const RESET_DRAW = 'GAME/RESET_DRAW'

// metadata
export const SET_GAMESETTINGS = 'METADATA/SET_GAMESETTINGS'
export const SET_CURSORS = 'METADATA/SET_CURSORS'
export const UPDATE_CURSOR = 'METADATA/UPDATE_CURSOR'
export const SET_LAST_COORDINATES = 'METADATA/SET_LAST_COORDINATES'
export const SET_DOWN_COORDINATES = 'METADATA/SET_DOWN_COORDINATES'

// chat
export const ADD_CHAT_MESSAGE = 'CHAT/ADD_CHAT_MESSAGE'
export const SET_CHAT_USERNAME = 'CHAT/SET_CHAT_USERNAME'
export const OVERWRITE_CHAT = 'CHAT/OVERWRITE_CHAT'

// user
export const SET_USERS_FROM_API = 'USER/SET_USERS_FROM_API'

// character
export const ADD_CHARACTER = 'CHARACTER/ADD_CHARACTER'
export const UPDATE_CHARACTER = 'CHARACTER/UPDATE_CHARACTER'
export const DELETE_CHARACTER = 'CHARACTER/DELETE_CHARACTER'
export const ASSIGN_CHARACTER = 'CHARACTER/ASSIGN_CHARACTER'
export const ASSIGN_CHARACTER_TO_USER = 'CHARACTER/ASSIGN_CHARACTER_TO_USER'
export const SET_CHARACTERS = 'CHARACTER/SET_CHARACTERS'
