// Websocket Tasks
export const WEBSOCKET_OPEN_CONNECTION = 'WS/OPEN_CONNECTION'

// API Tasks
export const API_LOAD_ROOM = 'API/LOAD_ROOM'
export const API_LOAD_MAPS = 'API/LOAD_MAPS'
export const API_LOAD_TOKENS = 'API/LOAD_TOKENS'
export const API_LOAD_CHAT = 'API/LOAD_CHAT'
export const API_LOAD_CHARACTERS = 'API/LOAD_CHARACTERS'
export const API_LOAD_USERS = 'API/LOAD_USERS'
export const API_SAVE_ROOM = 'API/SAVE_ROOM'
export const API_SAVE_MAPS = 'API/SAVE_MAPS'
export const API_SAVE_TOKENS = 'API/SAVE_TOKENS'
export const API_SAVE_CHAT = 'API/SAVE_CHAT'
export const API_SAVE_CHARACTERS = 'API/SAVE_CHARACTERS'
export const API_SAVE_USERS = 'API/SAVE_USERS'
export const API_AUTHENTICATING_USER = 'API/AUTHENTICATING_USER'
export const API_REGISTERING_USER = 'API/REGISTERING_USER'
export const API_STARTING_SESSION = 'API/STARTING_SESSION'

// Character Tasks
export const CHARACTER_SAVE = 'CHARACTER/SAVE'

// Game State Tasks
export const GAME_REQUEST_REFRESH = 'GAME/REQUEST_REFRESH'
export const GAME_LOAD_MAP = 'GAME/LOAD_MAP'
