// Websocket Tasks
export const WEBSOCKET_OPEN_CONNECTION = 'WS/OPEN_CONNECTION'

// API Tasks
export const API_LOAD_ROOM = 'API/LOAD_ROOM'
export const API_LOAD_MAPS = 'API/LOAD_MAPS'
export const API_LOAD_TOKENS = 'API/LOAD_TOKENS'
export const API_LOAD_CHAT = 'API/LOAD_CHAT'
export const API_LOAD_CHARACTERS = 'API/LOAD_CHARACTERS'
export const API_LOAD_USERS = 'API/LOAD_USERS'
export const API_AUTHENTICATING_USER = 'API/AUTHENTICATING_USER'

// Character Tasks
export const CHARACTER_SAVE = 'CHARACTER/SAVE'

// Game State Tasks
export const GAME_REQUEST_REFRESH = 'GAME/REQUEST_REFRESH'
export const GAME_LOAD_MAP = 'GAME/LOAD_MAP'
